version: "3.9"

services:
  firebird:
    image: jacobalberty/firebird:2.5-sc
    environment:
      - ISC_PASSWORD=3122414422
      - FIREBIRD_DATABASE=test.gdb
      - EnableLegacyClientAuth=true
    volumes:
      - ./firebird/data:/firebird/data
      - ./firebird/conf:/firebird/etc
    ports:
      - "3050:3050"   
    networks:
      - traefik
    deploy:
      placement:
        constraints: ["${NODE}"]      
    restart: unless-stopped
    logging:
      driver: loki
      options:
        loki-url: ${LOKI_URL}  

  filebrowser:
    image: filebrowser/filebrowser:latest
    container_name: filebrowser
    user: 1000:1000
    volumes:
      - ./firebird/data:/srv   # Carpeta compartida con Firebird
      - ./filebrowser/config:/config
      - ./filebrowser/database:/database
    ports:
      - "5003:80"
    restart: unless-stopped
