version: "3.9"

services:
  firebird:
    image: jacobalberty/firebird:2.5-sc
    environment:
      - ISC_PASSWORD=3122414422
    volumes:
      - firebird_data:/firebird/data
    ports:
      - "3050:3050"   
    networks:
      - traefik
    deploy:
      placement:
        constraints: ["${NODE}"]      
    restart: unless-stopped
    logging:
      driver: loki
      options:
        loki-url: ${LOKI_URL}  

  sftp:
    image: linuxserver/openssh-server
    volumes:
      - /srv/firebird_data:/home/sftp-user/data
    ports:
      - "2222:2222"
    environment:
      - PUID=1001                  # UID del usuario limitado
      - PGID=1001                  # GID del usuario limitado
      - TZ=America/Argentina/Buenos_Aires
      - USER_NAME=sftp-user         # usuario para SFTP
      - USER_PASSWORD=admin
      - PASSWORD_ACCESS=true   
      - SUDO_ACCESS=false
    restart: unless-stopped
volumes:
  firebird_data:
    driver: local
    name: "${SERVICE_NAME}_firebird_data"
networks:
  traefik:
    external:
      name: traefik    
