version: "3.9"

services:
  firebird:
    image: jacobalberty/firebird:2.5-sc
    environment:
      - ISC_PASSWORD=3122414422
    volumes:
      - firebird_data:/firebird/data   
    networks:
      - traefik
    deploy:
      placement:
        constraints: ["${NODE}"]  
      ports:
        - target: 3050
          published: 3050
          protocol: tcp
          mode: host  # O 'ingress' si quieres balanceador  
    restart: unless-stopped
    logging:
      driver: loki
      options:
        loki-url: ${LOKI_URL}  

  sftp:
    image: atmoz/sftp
    volumes:
      - firebird_data:/home/sftp-user/firebird-data  
    ports:
      - "2222:22"
    command: "sftp-user:admin:1001:1001:firebird-data"
    deploy:
      placement:
        constraints: ["${NODE}"]      
    restart: unless-stopped
    
volumes:
  firebird_data:
    driver: local
    name: "${SERVICE_NAME}_firebird_data"
networks:
  traefik:
    external:
      name: traefik    
