version: "3.9"

services:
  firebird:
    image: jacobalberty/firebird:2.5-sc
    environment:
      - ISC_PASSWORD=3122414422
    volumes:
      - firebird_data:/firebird/data
      - firebird_conf:/firebird/etc
    ports:
      - "3050:3050"   
    networks:
      - traefik
    deploy:
      placement:
        constraints: ["${NODE}"]      
    restart: unless-stopped
    logging:
      driver: loki
      options:
        loki-url: ${LOKI_URL}  

  filebrowser:
    image: filebrowser/filebrowser:latest
    networks:
      - traefik
    user: 1000:1000
    volumes:
      - firebird_data:/srv   # comparte el mismo volumen con Firebird
      - filebrowser_config:/config
      - filebrowser_db:/database
    ports:
      - "5003:80"
    restart: unless-stopped
volumes:
  firebird_data:
    name: "${SERVICE_NAME}_firebird_data"
  firebird_conf:
    name: "${SERVICE_NAME}_firebird_conf"
  filebrowser_config:
    name: "${SERVICE_NAME}_filebrowser_config"
  filebrowser_db:
    name: "${SERVICE_NAME}_filebrowser_db"
networks:
  traefik:
    external:
      name: traefik    
