version: "3.9"

services:
  firebird:
    image: jacobalberty/firebird:2.5-sc
    environment:
      - ISC_PASSWORD=3122414422
    volumes:
      - firebird_data:/firebird/data
    ports:
      - "3050:3050"   
    networks:
      - traefik
    deploy:
      placement:
        constraints: ["${NODE}"]      
    restart: unless-stopped
    logging:
      driver: loki
      options:
        loki-url: ${LOKI_URL}  

  sftp:
    image: atmoz/sftp
    container_name: sftp
    volumes:
      - firebird_data:/home/data:rw   # comparte el volumen con Firebird
    ports:
      - "2222:22"
    command: user:password:1001   # user/pass para conectarte
    restart: unless-stopped
volumes:
  firebird_data:
    name: "${SERVICE_NAME}_firebird_data"
networks:
  traefik:
    external:
      name: traefik    
