version: "3.9"

services:
  firebird:
    image: jacobalberty/firebird:2.5-sc
    environment:
      - ISC_PASSWORD=3122414422
    volumes:
      - /srv/firebird_data:/firebird/data
    ports:
      - "3050:3050"   
    networks:
      - traefik
    deploy:
      placement:
        constraints: ["${NODE}"]      
    restart: unless-stopped
    logging:
      driver: loki
      options:
        loki-url: ${LOKI_URL}  

  sftp:
    image: atmoz/sftp
    container_name: sftp
    volumes:
      - /srv/firebird_data:/home/data
    ports:
      - "2222:22"
    command: sftp-user:admin:1001  
    restart: unless-stopped
networks:
  traefik:
    external:
      name: traefik    
